const CACHE_VERSION="woa-pwa-20261006-0154";
const RUNTIME_CACHE="woa-runtime-20261006-0154";
const CORE=["index.html","offline.html","manifest.webmanifest","assets/css/style-v20260914-6.css","assets/js/search-v20260914-6.js","assets/js/search-index.json","assets/icons/icon-192.png","assets/icons/icon-512.png","about.html","companion/index.html","companion/assets/companion-v20260916-1.css","companion/assets/companion-v20260916-1.js","changelog.html","start-here.html","rules/index.html","rules/status.html","world/index.html","vtt-prototype/index.html","vtt-prototype/style.css","vtt-prototype/app.js"];
let PRECACHE=[];
function scopedUrl(path){return new URL(path,self.registration.scope).href;}
async function cachedMatch(request){return caches.match(request,{ignoreSearch:true});}
function normalizePath(path){if(!path)return "index.html";try{const u=new URL(path,self.registration.scope);let rel=u.pathname.replace(new URL(self.registration.scope).pathname,"").replace(/^\//,"");if(!rel)rel="index.html";if(rel.endsWith("/"))rel+="index.html";return rel;}catch(_){return String(path).replace(/^\.\//,"").replace(/^\//,"");}}
async function buildPrecache(){const paths=new Set(CORE);try{const res=await fetch(scopedUrl("assets/js/search-index.json"),{cache:"reload"});if(res.ok){const data=await res.json();for(const item of Array.isArray(data)?data:[]){if(item&&item.url)paths.add(normalizePath(item.url));}}}catch(_){ }PRECACHE=[...paths];}
async function networkFirst(request,navigation=false){const runtime=await caches.open(RUNTIME_CACHE);try{const res=await fetch(request,{cache:"reload"});if(res.ok)await runtime.put(request,res.clone());return res;}catch(_){const exact=await cachedMatch(request);if(exact)return exact;if(navigation){const u=new URL(request.url);let rel=u.pathname.replace(new URL(self.registration.scope).pathname,"").replace(/^\//,"");if(!rel)rel="index.html";if(rel.endsWith("/"))rel+="index.html";const normalized=await cachedMatch(scopedUrl(rel));if(normalized)return normalized;}return undefined;}}
async function cacheFirst(request){const cached=await cachedMatch(request);if(cached)return cached;try{const res=await fetch(request);if(res.ok){const runtime=await caches.open(RUNTIME_CACHE);await runtime.put(request,res.clone());}return res;}catch(_){return cached;}}
self.addEventListener("install",event=>event.waitUntil((async()=>{await buildPrecache();const cache=await caches.open(CACHE_VERSION);for(const path of PRECACHE){const req=new Request(scopedUrl(path),{cache:"reload"});const res=await fetch(req);if(!res.ok)throw new Error(`WoA offline precache failed for ${path}`);await cache.put(req,res.clone());}await self.skipWaiting();})()));
self.addEventListener("activate",event=>event.waitUntil((async()=>{const names=await caches.keys();await Promise.all(names.filter(n=>n.startsWith("woa-")&&!([CACHE_VERSION,RUNTIME_CACHE].includes(n))).map(n=>caches.delete(n)));await self.clients.claim();})()));
self.addEventListener("fetch",event=>{const request=event.request;if(request.method!=="GET")return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;const html=request.mode==="navigate"||(request.headers.get("accept")||"").includes("text/html");if(html){event.respondWith((async()=>{const res=await networkFirst(request,true);return res||(await cachedMatch(scopedUrl("offline.html")))||Response.error();})());return;}if(request.destination==="script"||request.destination==="style"){event.respondWith(networkFirst(request));return;}if(request.destination==="image"||request.destination==="font"){event.respondWith(cacheFirst(request));}});
self.addEventListener("message",event=>{if(!event.data)return;if(event.data.type==="WOA_FORCE_REFRESH"){event.waitUntil((async()=>{const names=await caches.keys();await Promise.all(names.filter(n=>n.startsWith("woa-")).map(n=>caches.delete(n)));await self.skipWaiting();})());return;}if(event.data.type!=="WOA_CACHE_STATUS")return;event.waitUntil((async()=>{await buildPrecache();let cached=0;try{const cache=await caches.open(CACHE_VERSION);const keys=await cache.keys();const expected=new Set(PRECACHE.map(scopedUrl));cached=keys.reduce((n,r)=>n+(expected.has(r.url)?1:0),0);}catch(_){}const payload={type:"WOA_CACHE_STATUS",ready:cached===PRECACHE.length&&PRECACHE.length>0,cached,total:PRECACHE.length,version:CACHE_VERSION,updated:"5 Oct 2026"};if(event.ports&&event.ports[0])event.ports[0].postMessage(payload);else if(event.source)event.source.postMessage(payload);})());});
