const sessionRoleEl=document.getElementById('session-role'),sessionPlayerNameEl=document.getElementById('session-player-name'),playerNameWrap=document.getElementById('player-name-wrap'),permissionStatusEl=document.getElementById('permission-status');
const tokenNameEl=document.getElementById('token-name'),tokenGlyphEl=document.getElementById('token-glyph'),tokenColorEl=document.getElementById('token-color'),tokenFootprintEl=document.getElementById('token-footprint'),tokenAssignmentEl=document.getElementById('token-assignment'),tokenPlayersEl=document.getElementById('token-players');
const canvas=document.getElementById('scene'),ctx=canvas?.getContext('2d'),selectionEl=document.getElementById('selection'),altitudeEl=document.getElementById('altitude'),movementEl=document.getElementById('movement-readout'),tokenList=document.getElementById('tokens');
const FEET_PER_GRID=5,ALTITUDE_STEP=5,MAX_ALTITUDE=120,MIN_ZOOM=.35,MAX_ZOOM=10,GRID_RADIUS=20,CELL_PX=42,NEAR=.5;
const terrainTypeEl=document.getElementById('terrain-type'),terrainHeightEl=document.getElementById('terrain-height'),terrainStatusEl=document.getElementById('terrain-status');
function applyMobileLayout(){const narrow=window.innerWidth<=520,layout=document.querySelector('.layout'),stage=document.querySelector('.stage-card'),panel=document.querySelector('.panel');if(!layout||!stage||!panel)return;if(narrow){Object.assign(layout.style,{display:'flex',flexDirection:'column',width:'100%',minWidth:'0',height:'auto',minHeight:'0'});Object.assign(stage.style,{order:'1',width:'100%',minWidth:'0',height:'58dvh',minHeight:'320px',flex:'none',borderRight:'0'});Object.assign(panel.style,{order:'2',width:'100%',minWidth:'0',maxWidth:'100%',height:'auto',minHeight:'0',maxHeight:'none',display:'block',overflow:'visible'});}else{layout.style.removeProperty('display');layout.style.removeProperty('flex-direction');layout.style.removeProperty('width');layout.style.removeProperty('min-width');layout.style.removeProperty('height');layout.style.removeProperty('min-height');stage.style.removeProperty('order');stage.style.removeProperty('width');stage.style.removeProperty('min-width');stage.style.removeProperty('height');stage.style.removeProperty('min-height');stage.style.removeProperty('flex');stage.style.removeProperty('border-right');panel.style.removeProperty('order');panel.style.removeProperty('width');panel.style.removeProperty('min-width');panel.style.removeProperty('max-width');panel.style.removeProperty('height');panel.style.removeProperty('min-height');panel.style.removeProperty('max-height');panel.style.removeProperty('display');panel.style.removeProperty('overflow');}}
addEventListener('resize',applyMobileLayout);applyMobileLayout();
const state={camera:{yaw:-.65,elevation:.68,distance:60,zoom:1,targetX:0,targetY:0,targetZ:0,panX:0,panY:0},selected:'ranger',drag:null,pointers:new Map(),pinchDistance:null,lastPinchMid:null,view2d:false,panMode:false,movingToken:null,moveOffset:{x:0,y:0},moveStart:null,moveDistance:0,terrain:{},terrainMode:false,tokens:[{id:'ranger',name:'Ranger',x:-4,y:1,z:60,glyph:'R',size:1,color:'#65d6a1',footprint:1,assignment:'all',players:[]},{id:'balaur',name:'Balaur Soldier',x:3,y:0,z:30,glyph:'B',size:1,color:'#e06b6b',footprint:1,assignment:'gm',players:[]},{id:'enemy',name:'Aerial Enemy',x:1,y:-3,z:90,glyph:'E',size:1,color:'#e3b65b',footprint:1,assignment:'unassigned',players:[]}]};
function resize(){if(!ctx)return;const d=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect(),w=Math.max(1,r.width),h=Math.max(1,r.height);canvas.width=Math.round(w*d);canvas.height=Math.round(h*d);ctx.setTransform(d,0,0,d,0,0)}
addEventListener('resize',resize);resize();
function size(){const r=canvas.getBoundingClientRect();return{w:Math.max(1,r.width),h:Math.max(1,r.height)}}
function tokenWorld(t){const f=Math.max(1,t.footprint||1),bx=t._dragX??t.x,by=t._dragY??t.y;return{x:bx+(f-1)/2,y:by+(f-1)/2}}
function basis(){const c=state.camera,cp=Math.cos(c.elevation),sp=Math.sin(c.elevation),sy=Math.sin(c.yaw),cy=Math.cos(c.yaw);const f={x:sy*cp,y:cy*cp,z:-sp},r={x:cy,y:-sy,z:0},u={x:r.y*f.z,y:-r.x*f.z,z:r.x*f.y-r.y*f.x},pos={x:c.targetX-f.x*c.distance,y:c.targetY-f.y*c.distance,z:c.targetZ/5-f.z*c.distance};return{pos,f,r,u}}
function project(x,y,z){const{w,h}=size();if(state.view2d)return{x:w/2+x*CELL_PX*state.camera.zoom+state.camera.panX,y:h/2-y*CELL_PX*state.camera.zoom+state.camera.panY,depth:1,scale:state.camera.zoom};const b=basis(),q={x:x-b.pos.x,y:y-b.pos.y,z:z/5-b.pos.z},cx=q.x*b.r.x+q.y*b.r.y+q.z*b.r.z,cy=q.x*b.u.x+q.y*b.u.y+q.z*b.u.z,depth=q.x*b.f.x+q.y*b.f.y+q.z*b.f.z,focal=Math.min(w,h)*.86*state.camera.zoom,s=focal/Math.max(NEAR,depth);return{x:w/2+cx*s,y:h*.56-cy*s,depth,scale:s/CELL_PX}}
function terrainHeightAt(x,y){const tile=state.terrain[snapCell(x)+','+snapCell(y)];return tile?tile.height:0}
function tokenProject(t){const p=tokenWorld(t);return project(p.x,p.y,terrainHeightAt(p.x,p.y)+t.z)}
function groundProject(t){const p=tokenWorld(t);return project(p.x,p.y,terrainHeightAt(p.x,p.y))}
function tokenRadius(t){const f=Math.max(1,t.footprint||1),p=groundProject(t);if(state.view2d)return Math.max(4,CELL_PX*state.camera.zoom*f*.5);if(!Number.isFinite(p.scale)||p.scale<=0)return 8;return Math.max(5,p.scale*CELL_PX*f*.5)}
const line=(a,b)=>{ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y)};
function gridPointValid(p){return Number.isFinite(p.x)&&Number.isFinite(p.y)&&Number.isFinite(p.depth)&&p.depth>NEAR&&Math.abs(p.x)<1e5&&Math.abs(p.y)<1e5}
function drawGridLine(points){let drawing=false,last=null;for(const p of points){const ok=gridPointValid(p);if(ok&&!drawing){ctx.beginPath();ctx.moveTo(p.x,p.y);drawing=true;last=p}else if(ok&&drawing){if(last&&Math.abs(p.x-last.x)<Math.max(250,window.innerWidth*2)&&Math.abs(p.y-last.y)<Math.max(250,window.innerHeight*2)){ctx.lineTo(p.x,p.y);last=p}else{ctx.stroke();ctx.beginPath();ctx.moveTo(p.x,p.y);last=p}}else if(drawing){ctx.stroke();drawing=false;last=null}}if(drawing)ctx.stroke()}
function grid(){ctx.save();ctx.beginPath();ctx.rect(0,0,size().w,size().h);ctx.clip();ctx.strokeStyle='rgba(143,211,255,.30)';ctx.lineWidth=1;for(let i=-GRID_RADIUS;i<=GRID_RADIUS;i++){const a=[],b=[];for(let s=0;s<=80;s++){const q=-GRID_RADIUS+(2*GRID_RADIUS*s/80);a.push(project(i-.5,q-.5,0));b.push(project(q-.5,i-.5,0))}drawGridLine(a);drawGridLine(b)}ctx.restore()}
function drawTerrain(){const palette={ground:'#58734d',hill:'#79965a',mountain:'#8b929c',cliff:'#77717a',canopy:'#286b45',platform:'#9a7955'};const shade=['#303943','#39434d','#424d58','#353e48'];const tiles=Object.entries(state.terrain).map(([key,t])=>{const xy=key.split(',').map(Number);return{key,x:xy[0],y:xy[1],type:t.type||'hill',height:Math.max(0,Math.min(120,Number(t.height)||0))};}).sort((a,b)=>{const pa=project(a.x,a.y,a.height),pb=project(b.x,b.y,b.height);return (pb.depth||0)-(pa.depth||0)});const poly=(pts,color)=>{if(pts.some(p=>!Number.isFinite(p.x)||!Number.isFinite(p.y)))return;ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);pts.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.closePath();ctx.fillStyle=color;ctx.fill();ctx.strokeStyle='#17212a';ctx.lineWidth=1;ctx.stroke()};for(const t of tiles){const x=t.x,y=t.y,z=t.height,corners=[[x-.5,y-.5],[x+.5,y-.5],[x+.5,y+.5],[x-.5,y+.5]],top=corners.map(p=>project(p[0],p[1],z));if(!state.view2d&&z>0){const neighbors=[[x,y-1],[x+1,y],[x,y+1],[x-1,y]];for(let i=0;i<4;i++){const n=state.terrain[neighbors[i][0]+','+neighbors[i][1]],bottomHeight=n?Math.min(z,Math.max(0,Number(n.height)||0)):0;if(bottomHeight>=z)continue;const j=(i+1)%4,lowA=project(corners[i][0],corners[i][1],bottomHeight),lowB=project(corners[j][0],corners[j][1],bottomHeight);poly([top[i],top[j],lowB,lowA],shade[i])}}poly(top,palette[t.type]||palette.hill);const c=project(x,y,z);if(c.depth>NEAR&&c.x>-100&&c.x<size().w+100&&c.y>-100&&c.y<size().h+100){ctx.fillStyle='#fff';ctx.font='700 10px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(t.type+' '+z+'ft',c.x,c.y)}}}
function ground(t){const g=groundProject(t),p=tokenProject(t);if(g.depth<=NEAR||p.depth<=NEAR)return;const f=Math.max(1,t.footprint||1),rr=Math.max(7,Math.min(32,7+g.scale*CELL_PX*f*.12));ctx.save();ctx.strokeStyle=t.id===state.selected?'rgba(255,255,255,.9)':'rgba(143,211,255,.7)';ctx.lineWidth=t.id===state.selected?2.5:1.5;ctx.setLineDash([5,5]);ctx.beginPath();line(g,p);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='rgba(3,7,13,.7)';ctx.beginPath();ctx.ellipse(g.x,g.y,rr,rr*.32,0,0,Math.PI*2);ctx.fill();ctx.stroke();if(t.z){ctx.fillStyle='#e6f0fa';ctx.font='700 9px system-ui';ctx.textAlign='center';ctx.textBaseline='bottom';ctx.fillText(`${t.z} ft`,g.x,g.y-rr-3)}ctx.restore()}
function drawToken(t){const p=tokenProject(t);if(!Number.isFinite(p.x)||!Number.isFinite(p.y)||p.depth<=NEAR)return;ground(t);const r=tokenRadius(t);if(!Number.isFinite(r)||r<=0)return;ctx.save();ctx.translate(p.x,p.y);ctx.shadowColor='rgba(0,0,0,.7)';ctx.shadowBlur=6;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fillStyle=t.color||'#7aa7ff';ctx.fill();ctx.shadowBlur=0;ctx.lineWidth=t.id===state.selected?4:2;ctx.strokeStyle=t.id===state.selected?'#fff':'#0b1320';ctx.stroke();ctx.fillStyle='#08111d';ctx.font=`800 ${Math.max(12,r*.72)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(t.glyph||'•',0,-2);ctx.fillStyle='#fff';ctx.font=`700 ${Math.max(8,Math.min(12,r*.3))}px system-ui`;ctx.fillText(`${t.z} ft`,0,r*.5);ctx.restore();t._screen={x:p.x,y:p.y,radius:r}}
function resetCamera(){state.camera={yaw:-.65,elevation:.68,distance:60,zoom:1,targetX:0,targetY:0,targetZ:0,panX:0,panY:0};state.drag=null;state.pointers.clear();state.pinchDistance=null;state.lastPinchMid=null;state.movingToken=null;state.moveStart=null;state.panMode=false;document.querySelectorAll('[data-action="toggle-pan"]').forEach(x=>{x.textContent='Pan: Off';x.setAttribute('aria-pressed','false');x.classList.remove('active')});resize()}
function drawMovementRuler(){if(!state.movingToken||!state.moveStart)return;const t=state.movingToken,f=Math.max(1,t.footprint||1),sx=state.moveStart.x,sy=state.moveStart.y,ex=snapCell(t._dragX??t.x),ey=snapCell(t._dragY??t.y);const start={...t,x:sx,y:sy},end={...t,x:ex,y:ey};const a=tokenProject(start),b=tokenProject(end);if(!Number.isFinite(a.x)||!Number.isFinite(b.x)||a.depth<=NEAR||b.depth<=NEAR)return;const squares=Math.max(Math.abs(ex-sx),Math.abs(ey-sy)),feet=squares*FEET_PER_GRID;ctx.save();ctx.strokeStyle='rgba(255,235,120,.95)';ctx.fillStyle='rgba(255,235,120,.95)';ctx.lineWidth=3;ctx.setLineDash([8,6]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(b.x,b.y,Math.max(6,tokenRadius(t)*.28),0,Math.PI*2);ctx.fill();const mx=(a.x+b.x)/2,my=(a.y+b.y)/2-12;ctx.font='700 13px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';const label=`${feet} ft · ${squares} square${squares===1?'':'s'}`;const tw=ctx.measureText(label).width+16;ctx.fillStyle='rgba(5,8,15,.9)';ctx.beginPath();ctx.roundRect(mx-tw/2,my-12,tw,24,7);ctx.fill();ctx.fillStyle='#fff';ctx.fillText(label,mx,my);ctx.restore()}
function render(){const{w,h}=size();ctx.clearRect(0,0,w,h);ctx.fillStyle='#101927';ctx.fillRect(0,0,w,h);grid();drawTerrain();visibleTokens().sort((a,b)=>tokenProject(b).depth-tokenProject(a).depth).forEach(drawToken);drawMovementRuler();const hud=document.getElementById('camera-readout');if(hud)hud.textContent=`${state.view2d?'2D':'3D'} · Each grid = ${FEET_PER_GRID} ft · zoom ${state.camera.zoom.toFixed(2)}×`;if(movementEl){if(state.movingToken)movementEl.textContent=`Movement: ${state.moveDistance} ft · ${Math.ceil(state.moveDistance/FEET_PER_GRID)} square${Math.ceil(state.moveDistance/FEET_PER_GRID)===1?'':'s'}`;else if(state.moveDistance)movementEl.textContent=`Last movement: ${state.moveDistance} ft · ${Math.ceil(state.moveDistance/FEET_PER_GRID)} square${Math.ceil(state.moveDistance/FEET_PER_GRID)===1?'':'s'}`;else movementEl.textContent='Movement: —'}requestAnimationFrame(render)}requestAnimationFrame(render);
function isGM(){return sessionRoleEl.value==='gm'}
function currentPlayer(){return sessionPlayerNameEl.value.trim().toLowerCase()}
function canSeeToken(t){if(isGM())return true;if(t.assignment==='gm')return false;if(t.assignment==='specific')return (t.players||[]).some(p=>p.trim().toLowerCase()===currentPlayer());return true}
function canControlToken(t){if(isGM())return true;if(t.assignment==='all')return true;if(t.assignment==='specific')return (t.players||[]).some(p=>p.trim().toLowerCase()===currentPlayer());return false}
function visibleTokens(){return state.tokens.filter(canSeeToken)}
function updateIdentityUI(){const gm=isGM();playerNameWrap.hidden=gm;permissionStatusEl.textContent=gm?'GM preview: all tokens and management controls are available.':'Player preview: GM-only tokens are hidden; you can control All Players tokens and tokens assigned to your name. Unassigned tokens are visible but not controllable.';document.querySelectorAll('[data-action="token-add"],[data-action="token-update"],[data-action="token-delete"],[data-action="save-scene"],[data-action="load-scene"],[data-action="export-scene"],[data-action="import-scene"],[data-action="terrain-toggle"]').forEach(b=>b.disabled=!gm);if(!gm&&state.terrainMode){state.terrainMode=false;const terrainButton=document.querySelector('[data-action="terrain-toggle"]');if(terrainButton){terrainButton.textContent="Paint Terrain: Off";terrainButton.classList.remove("active");}}const t=state.tokens.find(x=>x.id===state.selected);if(t&&!canSeeToken(t)){state.selected=visibleTokens()[0]?.id||null;state.movingToken=null;state.moveStart=null}list()}
sessionRoleEl.onchange=updateIdentityUI;sessionPlayerNameEl.oninput=updateIdentityUI;
function assignmentLabel(t){if(t.assignment==='specific')return t.players?.length?`Players: ${t.players.join(", ")}`:'Specific players';if(t.assignment==='gm')return 'GM Only';if(t.assignment==='unassigned')return 'Unassigned';return 'All Players'}
function loadEditor(t){if(!t)return;tokenNameEl.value=t.name;tokenGlyphEl.value=t.glyph||'';tokenColorEl.value=t.color||'#65d6a1';tokenFootprintEl.value=String(t.footprint||1);tokenAssignmentEl.value=t.assignment||'all';tokenPlayersEl.value=(t.players||[]).join(', ');tokenPlayersEl.hidden=tokenAssignmentEl.value!=='specific'}
function select(id){const t=state.tokens.find(x=>x.id===id);if(!t||!canSeeToken(t))return;state.selected=id;const p=tokenWorld(t);selectionEl.textContent=`${t.name} · X ${p.x*FEET_PER_GRID} ft · Y ${p.y*FEET_PER_GRID} ft · Z ${t.z} ft · ${t.footprint||1}×${t.footprint||1} squares · ${assignmentLabel(t)}`;altitudeEl.textContent=`Altitude: ${t.z} ft`;[...tokenList.children].forEach(e=>e.classList.toggle('selected',e.dataset.id===id));loadEditor(t)}
function list(){tokenList.innerHTML='';visibleTokens().forEach(t=>{const e=document.createElement('div');e.className='token';e.dataset.id=t.id;const p=tokenWorld(t),f=t.footprint||1;e.innerHTML=`<span>${t.name}<small>${assignmentLabel(t)}</small></span><small>${t.z} ft · (${p.x*FEET_PER_GRID}, ${p.y*FEET_PER_GRID}) · ${f}×${f} squares</small>`;e.onclick=()=>select(t.id);tokenList.appendChild(e)});select(state.selected)}
list();
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),mid=(a,b)=>({x:(a.x+b.x)/2,y:(a.y+b.y)/2});
function hit(x,y){let out=null,bd=1e9;const touchPad=window.matchMedia&&window.matchMedia('(pointer:coarse)').matches?14:6;for(const t of visibleTokens()){const s=t._screen;if(s){const d=Math.hypot(x-s.x,y-s.y);if(d<=s.radius+touchPad&&d<bd){bd=d;out=t}}}return out}
function screenToGround(sx,sy){const{w,h}=size();if(state.view2d)return{x:(sx-w/2-state.camera.panX)/(CELL_PX*state.camera.zoom),y:-(sy-h/2-state.camera.panY)/(CELL_PX*state.camera.zoom)};const b=basis(),f=Math.min(w,h)*.86*state.camera.zoom,nx=(sx-w/2)/f,ny=-(sy-h*.56)/f,dir={x:b.f.x+nx*b.r.x+ny*b.u.x,y:b.f.y+nx*b.r.y+ny*b.u.y,z:b.f.z+nx*b.r.z+ny*b.u.z};if(Math.abs(dir.z)<.001)return{x:0,y:0};const tt=-b.pos.z/dir.z;return{x:b.pos.x+dir.x*tt,y:b.pos.y+dir.y*tt}}
function snapCell(v){return Math.floor(v+0.5)}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();canvas.setPointerCapture(e.pointerId);state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(state.pointers.size===1&&e.button===2&&isGM()){const g=screenToGround(x,y),cx=snapCell(g.x),cy=snapCell(g.y),key=cx+','+cy;if(state.terrain[key]){delete state.terrain[key];terrainStatusEl.textContent='Erased terrain at ('+cx+', '+cy+').'}else terrainStatusEl.textContent='No terrain tile at ('+cx+', '+cy+').';state.drag=null;state.movingToken=null;state.moveStart=null;state.pointers.delete(e.pointerId);return}if(state.pointers.size===1&&e.button===1){state.drag={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false,mode:state.view2d?'pan':'rotate'};state.movingToken=null;state.moveStart=null;return}if(state.terrainMode&&isGM()&&e.button===0&&state.pointers.size===1){const g=screenToGround(x,y),cx=snapCell(g.x),cy=snapCell(g.y),key=cx+','+cy,type=terrainTypeEl.value,height=Number(terrainHeightEl.value)||0;if(type==='erase'){delete state.terrain[key];terrainStatusEl.textContent='Choose a terrain type to paint; right-click erases.'}else{state.terrain[key]={type,height};terrainStatusEl.textContent='Painted '+type+' at ('+cx+', '+cy+') · '+height+' ft.'}state.pointers.delete(e.pointerId);return}if(state.pointers.size===1){const t=hit(x,y);if(t&&canControlToken(t)){state.selected=t.id;select(t.id);state.movingToken=t;const g=screenToGround(x,y),tw=tokenWorld(t);state.moveOffset={x:tw.x-g.x,y:tw.y-g.y};state.moveStart={x:t.x,y:t.y};state.moveDistance=0;t._dragX=t.x;t._dragY=t.y}else state.drag={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false,mode:(!state.view2d&&state.panMode)?'pan':'rotate'}}else{const p=[...state.pointers.values()];state.pinchDistance=dist(p[0],p[1]);state.lastPinchMid=mid(p[0],p[1]);state.drag=null;state.movingToken=null;state.moveStart=null}},{passive:false});
canvas.addEventListener('pointermove',e=>{if(!state.pointers.has(e.pointerId))return;e.preventDefault();state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(state.movingToken&&state.pointers.size===1){const g=screenToGround(x,y),t=state.movingToken,f=Math.max(1,t.footprint||1),desiredX=g.x+state.moveOffset.x-(f-1)/2,desiredY=g.y+state.moveOffset.y-(f-1)/2;t._dragX=desiredX;t._dragY=desiredY;const snappedX=snapCell(desiredX),snappedY=snapCell(desiredY);if(state.moveStart)state.moveDistance=Math.max(Math.abs(snappedX-state.moveStart.x),Math.abs(snappedY-state.moveStart.y))*FEET_PER_GRID;select(t.id);return}if(state.pointers.size>1){const q=[...state.pointers.values()],d=dist(q[0],q[1]),m=mid(q[0],q[1]);if(state.pinchDistance){state.camera.zoom=Math.max(MIN_ZOOM,Math.min(MAX_ZOOM,state.camera.zoom*d/state.pinchDistance));if(state.lastPinchMid){if(state.view2d){state.camera.panX+=m.x-state.lastPinchMid.x;state.camera.panY+=m.y-state.lastPinchMid.y}else{state.camera.targetX-=(m.x-state.lastPinchMid.x)/(CELL_PX*state.camera.zoom);state.camera.targetY+=(m.y-state.lastPinchMid.y)/(CELL_PX*state.camera.zoom)}}}state.pinchDistance=d;state.lastPinchMid=m;return}if(!state.drag)return;const dx=e.clientX-state.drag.lastX,dy=e.clientY-state.drag.lastY;if(state.view2d){state.camera.panX+=dx;state.camera.panY+=dy}else if(state.drag.mode==='pan'){const scale=Math.max(1.5,Math.min(8,state.camera.distance/(8*state.camera.zoom)))*1.8;state.camera.targetX-=dx/(CELL_PX*state.camera.zoom)*scale;state.camera.targetY+=dy/(CELL_PX*state.camera.zoom)*scale}else{state.camera.yaw+=dx*.012;state.camera.elevation=Math.max(.38,Math.min(.95,state.camera.elevation+dy*.006))}state.drag.lastX=e.clientX;state.drag.lastY=e.clientY});
function end(e){if(state.movingToken){const t=state.movingToken;t.x=snapCell(t._dragX??t.x);t.y=snapCell(t._dragY??t.y);delete t._dragX;delete t._dragY;state.movingToken=null;state.moveStart=null;list()}state.pointers.delete(e.pointerId);if(!state.pointers.size){state.drag=null;state.pinchDistance=null;state.lastPinchMid=null}}canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('wheel',e=>{e.preventDefault();state.camera.zoom=Math.max(MIN_ZOOM,Math.min(MAX_ZOOM,state.camera.zoom*(e.deltaY>0?.9:1.11)))},{passive:false});
function editorData(){const assignment=tokenAssignmentEl.value;return{name:tokenNameEl.value.trim()||'New Token',glyph:tokenGlyphEl.value.trim().slice(0,2)||'•',color:tokenColorEl.value,footprint:Math.max(1,Math.min(4,Number(tokenFootprintEl.value)||1)),assignment,players:assignment==='specific'?tokenPlayersEl.value.split(',').map(x=>x.trim()).filter(Boolean):[]}}
tokenAssignmentEl.onchange=()=>{tokenPlayersEl.hidden=tokenAssignmentEl.value!=='specific'};
for(const b of document.querySelectorAll('button'))b.onclick=()=>{const a=b.dataset.action,t=state.tokens.find(x=>x.id===state.selected);if(!isGM()&&['token-add','token-update','token-delete'].includes(a))return;if((a==='up'||a==='down')&&t&&!canControlToken(t))return;if(a==='token-add'){const d=editorData(),n={id:'token-'+Date.now(),name:d.name,x:0,y:0,z:0,glyph:d.glyph,color:d.color,footprint:d.footprint,assignment:d.assignment,players:d.players};state.tokens.push(n);select(n.id);list();return}if(a==='token-update'&&t&&isGM()){Object.assign(t,editorData());list();select(t.id);return}if(a==='token-delete'&&t&&isGM()){const i=state.tokens.indexOf(t);if(i>=0)state.tokens.splice(i,1);state.selected=state.tokens[0]?.id||null;list();return}if(a==='terrain-toggle'&&isGM()){state.terrainMode=!state.terrainMode;b.textContent=state.terrainMode?'Paint Terrain: On':'Paint Terrain: Off';b.classList.toggle('active',state.terrainMode);terrainStatusEl.textContent=state.terrainMode?'Click grid squares to paint.':'Terrain painting paused.'}if(a==='reset')resetCamera();if(a==='toggle-pan'){state.panMode=!state.panMode;document.querySelectorAll('[data-action="toggle-pan"]').forEach(x=>{x.textContent=state.panMode?'Pan: On':'Pan: Off';x.setAttribute('aria-pressed',String(state.panMode));x.classList.toggle('active',state.panMode)})}if(a==='2d'){state.view2d=!state.view2d;state.camera.panX=0;state.camera.panY=0;if(!state.view2d){state.camera.targetX=0;state.camera.targetY=0}b.textContent=state.view2d?'3D View':'2D Fallback'}if(a==='up'&&t)t.z=Math.min(MAX_ALTITUDE,t.z+ALTITUDE_STEP);if(a==='down'&&t)t.z=Math.max(0,t.z-ALTITUDE_STEP);if(a==='yaw-left')state.camera.yaw-=.28;if(a==='yaw-right')state.camera.yaw+=.28;if(a==='pitch-up')state.camera.elevation=Math.min(.95,state.camera.elevation+.1);if(a==='pitch-down')state.camera.elevation=Math.max(.38,state.camera.elevation-.1);list()};

const SCENE_STORAGE_KEY='woa-vtt-scene-v1';
const sceneSaveStatus=document.getElementById('scene-save-status');
const sceneImportFile=document.getElementById('scene-import-file');
function sceneSnapshot(){
  return {format:'wings-of-atreia-vtt-scene',version:1,savedAt:new Date().toISOString(),
    terrain:state.terrain,
    tokens:state.tokens.map(t=>({id:String(t.id),name:String(t.name||'Token'),x:Number.isFinite(t._dragX)?t._dragX:Number(t.x)||0,y:Number.isFinite(t._dragY)?t._dragY:Number(t.y)||0,z:Math.max(0,Math.min(MAX_ALTITUDE,Number(t.z)||0)),glyph:String(t.glyph||'•'),color:/^#[0-9a-f]{6}$/i.test(t.color||'')?t.color:'#65d6a1',footprint:Math.max(1,Math.min(4,Math.round(Number(t.footprint)||1))),assignment:['gm','specific','all','unassigned'].includes(t.assignment)?t.assignment:'all',players:Array.isArray(t.players)?t.players.map(String):[]})),
    selected:state.selected,camera:{yaw:state.camera.yaw,elevation:state.camera.elevation,distance:state.camera.distance,zoom:state.camera.zoom,targetX:state.camera.targetX,targetY:state.camera.targetY,targetZ:state.camera.targetZ,panX:state.camera.panX,panY:state.camera.panY},
    view2d:state.view2d,panMode:state.panMode,identity:{role:sessionRoleEl.value,playerName:sessionPlayerNameEl.value}
  };
}
function validateScene(data){
  if(!data||data.format!=='wings-of-atreia-vtt-scene'||data.version!==1||!Array.isArray(data.tokens)||data.tokens.length>500)throw new Error('This is not a supported Wings of Atreia scene file.');
  const ids=new Set();
  const tokens=data.tokens.map((t,i)=>{
    if(!t||typeof t!=='object')throw new Error('Scene contains an invalid token.');
    const id=String(t.id||'token-'+i);if(ids.has(id))throw new Error('Scene contains duplicate token IDs.');ids.add(id);
    const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
    const assignment=['gm','specific','all','unassigned'].includes(t.assignment)?t.assignment:'all';
    return{id,name:String(t.name||'Token').slice(0,120),x:num(t.x),y:num(t.y),z:Math.max(0,Math.min(MAX_ALTITUDE,num(t.z))),glyph:String(t.glyph||'•').slice(0,2),color:/^#[0-9a-f]{6}$/i.test(t.color||'')?t.color:'#65d6a1',footprint:Math.max(1,Math.min(4,Math.round(num(t.footprint,1)))),assignment,players:Array.isArray(t.players)?t.players.map(p=>String(p).slice(0,80)).slice(0,50):[]};
  });
  const c=data.camera&&typeof data.camera==='object'?data.camera:{};
  const num=(v,d)=>Number.isFinite(Number(v))?Number(v):d;
  const camera={yaw:num(c.yaw,-.65),elevation:Math.max(.38,Math.min(.95,num(c.elevation,.68))),distance:Math.max(5,Math.min(500,num(c.distance,60))),zoom:Math.max(MIN_ZOOM,Math.min(MAX_ZOOM,num(c.zoom,1))),targetX:num(c.targetX,0),targetY:num(c.targetY,0),targetZ:num(c.targetZ,0),panX:num(c.panX,0),panY:num(c.panY,0)};
  const terrain={};if(data.terrain&&typeof data.terrain==='object')Object.entries(data.terrain).slice(0,5000).forEach(([key,t])=>{if(!/^-?\d+,-?\d+$/.test(key)||!t)return;const type=['ground','hill','mountain','cliff','canopy','platform'].includes(t.type)?t.type:'hill',height=Math.max(0,Math.min(120,Math.round((Number(t.height)||0)/5)*5));if(height)terrain[key]={type,height}});
  return{tokens,terrain,camera,selected:tokens.some(t=>t.id===data.selected)?data.selected:(tokens[0]?.id||null),view2d:!!data.view2d,panMode:!!data.panMode,identity:data.identity&&typeof data.identity==='object'?data.identity:{}};
}
function applyScene(data){
  const scene=validateScene(data);
  state.tokens=scene.tokens;state.terrain=scene.terrain;state.camera=scene.camera;state.selected=scene.selected;state.view2d=scene.view2d;state.panMode=scene.panMode;
  state.drag=null;state.pointers.clear();state.pinchDistance=null;state.lastPinchMid=null;state.movingToken=null;state.moveStart=null;state.moveDistance=0;
  if(scene.identity.role==='player'||scene.identity.role==='gm')sessionRoleEl.value=scene.identity.role;
  if(typeof scene.identity.playerName==='string')sessionPlayerNameEl.value=scene.identity.playerName;
  document.querySelectorAll('[data-action="toggle-pan"]').forEach(b=>{b.textContent=state.panMode?'Pan: On':'Pan: Off';b.setAttribute('aria-pressed',String(state.panMode));b.classList.toggle('active',state.panMode)});
  document.querySelectorAll('[data-action="2d"]').forEach(b=>b.textContent=state.view2d?'3D View':'2D Fallback');
  updateIdentityUI();resize();list();if(state.selected)select(state.selected);
}
function saveSceneToBrowser(){
  try{localStorage.setItem(SCENE_STORAGE_KEY,JSON.stringify(sceneSnapshot()));sceneSaveStatus.textContent='Scene saved in this browser on this device.'}
  catch(e){sceneSaveStatus.textContent='Could not save locally. Browser storage may be unavailable or full.'}
}
document.querySelector('[data-action="save-scene"]').onclick=saveSceneToBrowser;
document.querySelector('[data-action="load-scene"]').onclick=()=>{
  try{const raw=localStorage.getItem(SCENE_STORAGE_KEY);if(!raw){sceneSaveStatus.textContent='No saved scene found in this browser yet.';return}applyScene(JSON.parse(raw));sceneSaveStatus.textContent='Saved scene loaded.'}
  catch(e){sceneSaveStatus.textContent='Could not load the saved scene: '+(e.message||'invalid scene data')}
};
document.querySelector('[data-action="export-scene"]').onclick=()=>{
  try{const blob=new Blob([JSON.stringify(sceneSnapshot(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='wings-of-atreia-scene.json';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);sceneSaveStatus.textContent='Scene JSON export started.'}
  catch(e){sceneSaveStatus.textContent='Could not export the scene.'}
};
document.querySelector('[data-action="import-scene"]').onclick=()=>sceneImportFile.click();
sceneImportFile.addEventListener('change',async()=>{
  const file=sceneImportFile.files?.[0];if(!file)return;
  try{if(file.size>2_000_000)throw new Error('Scene file is too large (maximum 2 MB).');const data=JSON.parse(await file.text());applyScene(data);saveSceneToBrowser();sceneSaveStatus.textContent='Scene imported and saved in this browser.'}
  catch(e){sceneSaveStatus.textContent='Import failed: '+(e.message||'could not read scene file')}
  finally{sceneImportFile.value=''}
});
