const canvas=document.getElementById('scene'),ctx=canvas?.getContext('2d'),selectionEl=document.getElementById('selection'),altitudeEl=document.getElementById('altitude'),tokenList=document.getElementById('tokens');
const FEET_PER_GRID=5,ALTITUDE_STEP=5,MAX_ALTITUDE=120,MIN_ZOOM=.35,MAX_ZOOM=4,GRID_RADIUS=20,CELL_PX=42,NEAR=.5;
const state={camera:{yaw:-.65,elevation:.68,distance:60,zoom:1,targetX:0,targetY:0,targetZ:0,panX:0,panY:0},selected:'ranger',drag:null,pointers:new Map(),pinchDistance:null,lastPinchMid:null,view2d:false,movingToken:null,tokens:[{id:'ranger',name:'Ranger',x:-4,y:1,z:60,glyph:'R',size:1,color:'#65d6a1',footprint:1},{id:'balaur',name:'Balaur Soldier',x:3,y:0,z:30,glyph:'B',size:1,color:'#e06b6b',footprint:1},{id:'enemy',name:'Aerial Enemy',x:1,y:-3,z:90,glyph:'E',size:1,color:'#e3b65b',footprint:1}]};
function resize(){if(!ctx)return;const d=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect();canvas.width=Math.max(320,r.width)*d;canvas.height=Math.max(360,r.height)*d;ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resize);resize();
function size(){const r=canvas.getBoundingClientRect();return{w:Math.max(320,r.width),h:Math.max(360,r.height)}}
function tokenWorld(t){const f=t.footprint||1;return{x:t.x+f/2-.5,y:t.y+f/2-.5}}
function basis(){const c=state.camera,cp=Math.cos(c.elevation),sp=Math.sin(c.elevation),sy=Math.sin(c.yaw),cy=Math.cos(c.yaw);const f={x:sy*cp,y:cy*cp,z:-sp};const r={x:cy,y:-sy,z:0};const u={x:r.y*f.z,y:-r.x*f.z,z:r.x*f.y-r.y*f.x};const pos={x:c.targetX-f.x*c.distance,y:c.targetY-f.y*c.distance,z:c.targetZ/5-f.z*c.distance};return{pos,f,r,u}}
function project(x,y,z){const{w,h}=size();if(state.view2d)return{x:w/2+x*CELL_PX*state.camera.zoom+state.camera.panX,y:h/2-y*CELL_PX*state.camera.zoom+state.camera.panY,depth:1,scale:state.camera.zoom};const b=basis(),q={x:x-b.pos.x,y:y-b.pos.y,z:z/5-b.pos.z},cx=q.x*b.r.x+q.y*b.r.y+q.z*b.r.z,cy=q.x*b.u.x+q.y*b.u.y+q.z*b.u.z,depth=q.x*b.f.x+q.y*b.f.y+q.z*b.f.z,focal=Math.min(w,h)*.86*state.camera.zoom,s=focal/Math.max(NEAR,depth);return{x:w/2+cx*s,y:h*.56-cy*s,depth,scale:s/CELL_PX}}
function tokenProject(t){const p=tokenWorld(t);return project(p.x,p.y,t.z)}
function groundProject(t){const p=tokenWorld(t);return project(p.x,p.y,0)}
function tokenRadius(t){const f=t.footprint||1,c=tokenWorld(t);if(state.view2d)return CELL_PX*state.camera.zoom*f/2;const a=project(c.x-f/2,c.y,c.z),b=project(c.x+f/2,c.y,c.z),d=project(c.x,c.y-f/2,c.z),e=project(c.x,c.y+f/2,c.z);const horizontal=Math.hypot(a.x-b.x,a.y-b.y),vertical=Math.hypot(d.x-e.x,d.y-e.y);return Math.max(4,(horizontal+vertical)/4)}
const line=(a,b)=>{ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y)};
function drawGridLine(points){let drawing=false;for(const p of points){const ok=p.depth>NEAR;if(ok&&!drawing){ctx.beginPath();ctx.moveTo(p.x,p.y);drawing=true}else if(ok&&drawing)ctx.lineTo(p.x,p.y);else if(drawing){ctx.stroke();drawing=false}}if(drawing)ctx.stroke()}
function grid(){ctx.save();ctx.strokeStyle='rgba(143,211,255,.34)';ctx.lineWidth=1;for(let i=-GRID_RADIUS;i<=GRID_RADIUS;i++){const a=[],b=[];for(let s=0;s<=40;s++){const q=-GRID_RADIUS+(2*GRID_RADIUS*s/40);a.push(project(i-.5,q-.5,0));b.push(project(q-.5,i-.5,0))}drawGridLine(a);drawGridLine(b)}ctx.strokeStyle='rgba(143,211,255,.82)';ctx.lineWidth=2;const a=[],b=[];for(let s=0;s<=40;s++){const q=-GRID_RADIUS+(2*GRID_RADIUS*s/40);a.push(project(q-.5,-.5,0));b.push(project(-.5,q-.5,0))}drawGridLine(a);drawGridLine(b);ctx.restore()}
function ground(t){const g=groundProject(t),p=tokenProject(t);if(g.depth<=NEAR||p.depth<=NEAR)return;const f=t.footprint||1,rr=Math.max(7,Math.min(32,7+g.scale*CELL_PX*f*.12));ctx.save();ctx.strokeStyle=t.id===state.selected?'rgba(255,255,255,.9)':'rgba(143,211,255,.7)';ctx.lineWidth=t.id===state.selected?2.5:1.5;ctx.setLineDash([5,5]);ctx.beginPath();line(g,p);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='rgba(3,7,13,.7)';ctx.beginPath();ctx.ellipse(g.x,g.y,rr,rr*.32,0,0,Math.PI*2);ctx.fill();ctx.stroke();if(t.z){ctx.fillStyle='#e6f0fa';ctx.font='700 9px system-ui';ctx.textAlign='center';ctx.textBaseline='bottom';ctx.fillText(`${t.z} ft`,g.x,g.y-rr-3)}ctx.restore()}
function drawToken(t){const p=tokenProject(t);if(p.depth<=NEAR)return;ground(t);const r=tokenRadius(t);ctx.save();ctx.translate(p.x,p.y);ctx.shadowColor='rgba(0,0,0,.7)';ctx.shadowBlur=6;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fillStyle=t.color;ctx.fill();ctx.shadowBlur=0;ctx.lineWidth=t.id===state.selected?4:2;ctx.strokeStyle=t.id===state.selected?'#fff':'#0b1320';ctx.stroke();ctx.fillStyle='#08111d';ctx.font=`800 ${Math.max(12,r*.72)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(t.glyph,0,-2);ctx.fillStyle='#fff';ctx.font=`700 ${Math.max(8,Math.min(12,r*.3))}px system-ui`;ctx.fillText(`${t.z} ft`,0,r*.5);ctx.restore();t._screen={x:p.x,y:p.y,radius:r}}
function render(){const{w,h}=size();ctx.clearRect(0,0,w,h);ctx.fillStyle='#101927';ctx.fillRect(0,0,w,h);grid();[...state.tokens].sort((a,b)=>tokenProject(b).depth-tokenProject(a).depth).forEach(drawToken);const hud=document.getElementById('camera-readout');if(hud)hud.textContent=`${state.view2d?'2D':'3D'} · Each grid = ${FEET_PER_GRID} ft · zoom ${state.camera.zoom.toFixed(2)}×`;requestAnimationFrame(render)}requestAnimationFrame(render);
function select(id){state.selected=id;const t=state.tokens.find(x=>x.id===id);if(!t)return;const p=tokenWorld(t);selectionEl.textContent=`${t.name} · X ${p.x*FEET_PER_GRID} ft · Y ${p.y*FEET_PER_GRID} ft · Z ${t.z} ft · ${t.footprint||1}×${t.footprint||1} squares`;altitudeEl.textContent=`Altitude: ${t.z} ft`;[...tokenList.children].forEach(e=>e.classList.toggle('selected',e.dataset.id===id))}
function list(){tokenList.innerHTML='';state.tokens.forEach(t=>{const e=document.createElement('div');e.className='token';e.dataset.id=t.id;const p=tokenWorld(t),f=t.footprint||1;e.innerHTML=`<span>${t.name}</span><small>${t.z} ft · (${p.x*FEET_PER_GRID}, ${p.y*FEET_PER_GRID}) · ${f}×${f} squares</small>`;e.onclick=()=>select(t.id);tokenList.appendChild(e)});select(state.selected)}list();
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),mid=(a,b)=>({x:(a.x+b.x)/2,y:(a.y+b.y)/2});
function hit(x,y){let out=null,bd=1e9;for(const t of state.tokens){const s=t._screen;if(s){const d=Math.hypot(x-s.x,y-s.y);if(d<=s.radius&&d<bd){bd=d;out=t}}}return out}
function screenToGround(sx,sy){const{w,h}=size();if(state.view2d)return{x:Math.floor((sx-w/2-state.camera.panX)/(CELL_PX*state.camera.zoom)),y:Math.floor(-(sy-h/2-state.camera.panY)/(CELL_PX*state.camera.zoom))};const b=basis(),f=Math.min(w,h)*.86*state.camera.zoom,nx=(sx-w/2)/f,ny=-(sy-h*.56)/f,dir={x:b.f.x+nx*b.r.x+ny*b.u.x,y:b.f.y+nx*b.r.y+ny*b.u.y,z:b.f.z+nx*b.r.z+ny*b.u.z};if(Math.abs(dir.z)<.001)return{x:0,y:0};const tt=-b.pos.z/dir.z;return{x:Math.floor(b.pos.x+dir.x*tt),y:Math.floor(b.pos.y+dir.y*tt)}}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();canvas.setPointerCapture(e.pointerId);state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(state.pointers.size===1){const t=hit(x,y);if(t){state.selected=t.id;select(t.id);state.movingToken=t}else state.drag={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false}}else{const p=[...state.pointers.values()];state.pinchDistance=dist(p[0],p[1]);state.lastPinchMid=mid(p[0],p[1]);state.drag=null;state.movingToken=null}},{passive:false});
canvas.addEventListener('pointermove',e=>{if(!state.pointers.has(e.pointerId))return;e.preventDefault();state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(state.movingToken&&state.pointers.size===1){const p=screenToGround(x,y);state.movingToken.x=p.x;state.movingToken.y=p.y;return}if(state.pointers.size>1){const q=[...state.pointers.values()],d=dist(q[0],q[1]),m=mid(q[0],q[1]);if(state.pinchDistance){state.camera.zoom=Math.max(MIN_ZOOM,Math.min(MAX_ZOOM,state.camera.zoom*d/state.pinchDistance));if(state.lastPinchMid){if(state.view2d){state.camera.panX+=m.x-state.lastPinchMid.x;state.camera.panY+=m.y-state.lastPinchMid.y}else{state.camera.targetX-=(m.x-state.lastPinchMid.x)/(CELL_PX*state.camera.zoom);state.camera.targetY+=(m.y-state.lastPinchMid.y)/(CELL_PX*state.camera.zoom)}}}state.pinchDistance=d;state.lastPinchMid=m;return}if(!state.drag)return;const dx=e.clientX-state.drag.lastX,dy=e.clientY-state.drag.lastY;if(state.view2d){state.camera.panX+=dx;state.camera.panY+=dy}else{state.camera.yaw+=dx*.012;state.camera.elevation=Math.max(.38,Math.min(.95,state.camera.elevation+dy*.006))}state.drag.lastX=e.clientX;state.drag.lastY=e.clientY});
function end(e){if(state.movingToken){state.movingToken=null;list()}state.pointers.delete(e.pointerId);if(!state.pointers.size){state.drag=null;state.pinchDistance=null;state.lastPinchMid=null}}canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);canvas.addEventListener('wheel',e=>{e.preventDefault();state.camera.zoom=Math.max(MIN_ZOOM,Math.min(MAX_ZOOM,state.camera.zoom*(e.deltaY>0?.9:1.11)))},{passive:false});
for(const b of document.querySelectorAll('button'))b.onclick=()=>{const a=b.dataset.action,t=state.tokens.find(x=>x.id===state.selected);if(a==='reset'){state.camera={yaw:-.65,elevation:.68,distance:60,zoom:1,targetX:0,targetY:0,targetZ:0,panX:0,panY:0};state.view2d=false}if(a==='2d'){state.view2d=!state.view2d;b.textContent=state.view2d?'3D View':'2D Fallback'}if(a==='up'&&t)t.z=Math.min(MAX_ALTITUDE,t.z+ALTITUDE_STEP);if(a==='down'&&t)t.z=Math.max(0,t.z-ALTITUDE_STEP);if(a==='yaw-left')state.camera.yaw-=.28;if(a==='yaw-right')state.camera.yaw+=.28;if(a==='pitch-up')state.camera.elevation=Math.min(.95,state.camera.elevation+.1);if(a==='pitch-down')state.camera.elevation=Math.max(.38,state.camera.elevation-.1);list()};