const canvas=document.getElementById('scene'),ctx=canvas?.getContext('2d'),selectionEl=document.getElementById('selection'),altitudeEl=document.getElementById('altitude'),tokenList=document.getElementById('tokens');
const FEET_PER_GRID=5,ALTITUDE_STEP=5,MAX_ALTITUDE=120,MIN_ZOOM=.35,MAX_ZOOM=4,GRID_RADIUS=20,CELL_PX=42;
const state={camera:{yaw:-.65,elevation:.62,distance:18,zoom:1,targetX:0,targetY:0,targetZ:0,panX:0,panY:0},selected:'ranger',drag:null,pointers:new Map(),pinchDistance:null,lastPinchMid:null,view2d:false,movingToken:null,tokens:[{id:'ranger',name:'Ranger',x:-4,y:1,z:60,glyph:'R',size:1.25,color:'#65d6a1'},{id:'balaur',name:'Balaur Soldier',x:3,y:0,z:30,glyph:'B',size:1.25,color:'#e06b6b'},{id:'enemy',name:'Aerial Enemy',x:1,y:-3,z:90,glyph:'E',size:1.25,color:'#e3b65b'}]};
function resize(){if(!ctx)return;const d=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect();canvas.width=Math.max(320,r.width)*d;canvas.height=Math.max(360,r.height)*d;ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resize);resize();
function size(){const r=canvas.getBoundingClientRect();return{w:Math.max(320,r.width),h:Math.max(360,r.height)}}
function basis(){const c=state.camera,h=Math.cos(c.elevation)*c.distance,v=Math.sin(c.elevation)*c.distance,pos={x:c.targetX-Math.sin(c.yaw)*h,y:c.targetY-Math.cos(c.yaw)*h,z:c.targetZ/5+v};let f={x:c.targetX-pos.x,y:c.targetY-pos.y,z:c.targetZ/5-pos.z},fl=Math.hypot(f.x,f.y,f.z);f={x:f.x/fl,y:f.y/fl,z:f.z/fl};let r={x:f.y,y:-f.x,z:0},rl=Math.hypot(r.x,r.y);r={x:r.x/rl,y:r.y/rl,z:0};return{pos,f,r,u:{x:r.y*f.z,y:-r.x*f.z,z:r.x*f.y}}}
function project(x,y,z){const{w,h}=size();if(state.view2d)return{x:w/2+x*CELL_PX*state.camera.zoom+state.camera.panX,y:h/2-y*CELL_PX*state.camera.zoom+state.camera.panY,depth:1,scale:state.camera.zoom};const b=basis(),q={x:x-b.pos.x,y:y-b.pos.y,z:z/5-b.pos.z},cx=q.x*b.r.x+q.y*b.r.y+q.z*b.r.z,cy=q.x*b.u.x+q.y*b.u.y+q.z*b.u.z,depth=q.x*b.f.x+q.y*b.f.y+q.z*b.f.z,s=Math.min(w,h)*.86*state.camera.zoom/Math.max(.55,depth);return{x:w/2+cx*s,y:h*.56-cy*s,depth,scale:s/CELL_PX}}
function tokenProject(t){const g=project(t.x,t.y,0);if(state.view2d)return{...project(t.x,t.y,t.z),ground:g};const b=basis(),s=Math.min(size().w,size().h)*.86*state.camera.zoom/Math.max(.55,g.depth);return{x:g.x,y:g.y-(t.z/5)*b.u.z*s,depth:g.depth,scale:s/CELL_PX,ground:g}}
const line=(a,b)=>{ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y)};
function grid(){ctx.save();ctx.strokeStyle='rgba(143,211,255,.34)';for(let i=-GRID_RADIUS;i<=GRID_RADIUS;i++){for(const [a,b] of [[project(i,-GRID_RADIUS,0),project(i,GRID_RADIUS,0)],[project(-GRID_RADIUS,i,0),project(GRID_RADIUS,i,0)]]){if(a.depth>.2&&b.depth>.2){ctx.beginPath();line(a,b);ctx.stroke()}}}ctx.strokeStyle='rgba(143,211,255,.82)';ctx.lineWidth=2;const a=project(-GRID_RADIUS,0,0),b=project(GRID_RADIUS,0,0),c=project(0,-GRID_RADIUS,0),d=project(0,GRID_RADIUS,0);ctx.beginPath();line(a,b);line(c,d);ctx.stroke();ctx.restore()}
function ground(t){const g=project(t.x,t.y,0),p=tokenProject(t);if(g.depth<=.2)return;ctx.save();ctx.strokeStyle=t.id===state.selected?'rgba(255,255,255,.9)':'rgba(143,211,255,.7)';ctx.setLineDash([5,5]);ctx.beginPath();line(g,p);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='rgba(3,7,13,.7)';ctx.beginPath();ctx.ellipse(g.x,g.y,Math.max(7,7+g.scale*5),Math.max(3,(7+g.scale*5)*.32),0,0,Math.PI*2);ctx.fill();if(t.z){ctx.fillStyle='#e6f0fa';ctx.font='700 9px system-ui';ctx.textAlign='center';ctx.fillText(`${t.z} ft`,g.x,g.y-9)}ctx.restore()}
function drawToken(t){const p=tokenProject(t);if(p.depth<=.2)return;ground(t);const r=Math.max(10,Math.min(46,18*p.scale*t.size));ctx.save();ctx.translate(p.x,p.y);ctx.shadowColor='rgba(0,0,0,.7)';ctx.shadowBlur=6;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fillStyle=t.color;ctx.fill();ctx.shadowBlur=0;ctx.lineWidth=t.id===state.selected?4:2;ctx.strokeStyle=t.id===state.selected?'#fff':'#0b1320';ctx.stroke();ctx.fillStyle='#08111d';ctx.font=`800 ${Math.max(12,r*.72)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(t.glyph,0,-2);ctx.fillStyle='#fff';ctx.font=`700 ${Math.max(8,Math.min(12,r*.3))}px system-ui`;ctx.fillText(`${t.z} ft`,0,r*.5);ctx.restore();t._screen={x:p.x,y:p.y,radius:r}}
function render(){const{w,h}=size();ctx.clearRect(0,0,w,h);ctx.fillStyle='#101927';ctx.fillRect(0,0,w,h);grid();[...state.tokens].sort((a,b)=>tokenProject(b).depth-tokenProject(a).depth).forEach(drawToken);const hud=document.getElementById('camera-readout');if(hud)hud.textContent=`${state.view2d?'2D':'3D'} · Each grid = ${FEET_PER_GRID} ft · zoom ${state.camera.zoom.toFixed(2)}×`;requestAnimationFrame(render)}requestAnimationFrame(render);
function select(id){state.selected=id;const t=state.tokens.find(x=>x.id===id);if(!t)return;selectionEl.textContent=`${t.name} · X ${t.x*FEET_PER_GRID} ft · Y ${t.y*FEET_PER_GRID} ft · Z ${t.z} ft`;altitudeEl.textContent=`Altitude: ${t.z} ft`;[...tokenList.children].forEach(e=>e.classList.toggle('selected',e.dataset.id===id))}
function list(){tokenList.innerHTML='';state.tokens.forEach(t=>{const e=document.createElement('div');e.className='token';e.dataset.id=t.id;e.innerHTML=`<span>${t.name}</span><small>${t.z} ft · (${t.x*FEET_PER_GRID}, ${t.y*FEET_PER_GRID})</small>`;e.onclick=()=>select(t.id);tokenList.appendChild(e)});select(state.selected)}list();
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),mid=(a,b)=>({x:(a.x+b.x)/2,y:(a.y+b.y)/2});
function hit(x,y){let out=null,bd=1e9;for(const t of state.tokens){const s=t._screen;if(s){const d=Math.hypot(x-s.x,y-s.y);if(d<=s.radius&&d<bd){bd=d;out=t}}}return out}
function snap(v){return Math.round(v)}
function screenToGround(sx,sy){const{w,h}=size();if(state.view2d)return{x:snap((sx-w/2-state.camera.panX)/(CELL_PX*state.camera.zoom)),y:snap(-(sy-h/2-state.camera.panY)/(CELL_PX*state.camera.zoom))};const b=basis(),f=Math.min(w,h)*.86*state.camera.zoom,nx=(sx-w/2)/f,ny=-(sy-h*.56)/f,dir={x:b.f.x+nx*b.r.x+ny*b.u.x,y:b.f.y+nx*b.r.y+ny*b.u.y,z:b.f.z+nx*b.r.z+ny*b.u.z},t=-b.pos.z/dir.z;return{x:snap(b.pos.x+dir.x*t),y:snap(b.pos.y+dir.y*t)}}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();canvas.setPointerCapture(e.pointerId);state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(state.pointers.size===1){const t=hit(x,y);if(t){state.selected=t.id;select(t.id);state.movingToken=t}else state.drag={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false}}else{const p=[...state.pointers.values()];state.pinchDistance=dist(p[0],p[1]);state.lastPinchMid=mid(p[0],p[1]);state.drag=null;state.movingToken=null}},{passive:false});
canvas.addEventListener('pointermove',e=>{if(!state.pointers.has(e.pointerId))return;e.preventDefault();state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(state.movingToken&&state.pointers.size===1){const p=screenToGround(x,y);state.movingToken.x=p.x;state.movingToken.y=p.y;return}if(state.pointers.size>1){const q=[...state.pointers.values()],d=dist(q[0],q[1]),m=mid(q[0],q[1]);if(state.pinchDistance){state.camera.zoom=Math.max(MIN_ZOOM,Math.min(MAX_ZOOM,state.camera.zoom*d/state.pinchDistance));if(state.lastPinchMid){if(state.view2d){state.camera.panX+=m.x-state.lastPinchMid.x;state.camera.panY+=m.y-state.lastPinchMid.y}else{state.camera.targetX-=(m.x-state.lastPinchMid.x)/(CELL_PX*state.camera.zoom);state.camera.targetY+=(m.y-state.lastPinchMid.y)/(CELL_PX*state.camera.zoom)}}}state.pinchDistance=d;state.lastPinchMid=m;return}if(!state.drag)return;const dx=e.clientX-state.drag.lastX,dy=e.clientY-state.drag.lastY;if(state.view2d){state.camera.panX+=dx;state.camera.panY+=dy}else{state.camera.yaw+=dx*.012;state.camera.elevation=Math.max(.32,Math.min(1.05,state.camera.elevation+dy*.008))}state.drag.lastX=e.clientX;state.drag.lastY=e.clientY});
function end(e){if(state.movingToken){state.movingToken=null;list()}state.pointers.delete(e.pointerId);if(!state.pointers.size){state.drag=null;state.pinchDistance=null;state.lastPinchMid=null}}canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);canvas.addEventListener('wheel',e=>{e.preventDefault();state.camera.zoom=Math.max(MIN_ZOOM,Math.min(MAX_ZOOM,state.camera.zoom*(e.deltaY>0?.9:1.11)))},{passive:false});
for(const b of document.querySelectorAll('button'))b.onclick=()=>{const a=b.dataset.action,t=state.tokens.find(x=>x.id===state.selected);if(a==='reset'){state.camera={yaw:-.65,elevation:.62,distance:18,zoom:1,targetX:0,targetY:0,targetZ:0,panX:0,panY:0};state.view2d=false}if(a==='2d'){state.view2d=!state.view2d;b.textContent=state.view2d?'3D View':'2D Fallback'}if(a==='up'&&t)t.z=Math.min(MAX_ALTITUDE,t.z+ALTITUDE_STEP);if(a==='down'&&t)t.z=Math.max(0,t.z-ALTITUDE_STEP);if(a==='yaw-left')state.camera.yaw-=.28;if(a==='yaw-right')state.camera.yaw+=.28;if(a==='pitch-up')state.camera.elevation=Math.min(1.05,state.camera.elevation+.12);if(a==='pitch-down')state.camera.elevation=Math.max(.32,state.camera.elevation-.12);list()};
